services:
  reverse-proxy:
    platform: linux/amd64
    restart: on-failure
    network_mode: "host"
    build:
      context: ./proxy
      dockerfile: Dockerfile
      network: host
    # ports:
    #   - "${SSL_PORT}:443"
    #   - "${HTTP_PORT}:80"
    volumes:
      - /etc/letsencrypt/ssl/:/etc/nginx/ssl/

  webhook:
    platform: linux/amd64
    restart: on-failure
    network_mode: "hodt"
    build:
      context: ./webhook
      dockerfile: Dockerfile
      network: host
    ports:
      - 8080:8080
