import { getConfig } from "utils/dist/config"

const vitalKeys = [
  "NEXTAUTH_JWT_SECRET",
  "NEXTAUTH_SECRET",
  "NEXTAUTH_QBO_AUTH_PROVIDER_ID",

  "QBO_CLIENT_ID",
  "QBO_CLIENT_SECRET",
  "QBO_WELL_KNOWN",
  "QBO_BASE_API_ROUTE",
  "QBO_OAUTH_ROUTE",
  "QBO_ACCOUNTS_BASE_ROUTE",
  "QBO_OAUTH_REVOCATION_ENDPOINT",

  "STRIPE_PUBLIC_KEY",
  "STRIPE_PRIVATE_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "STRIPE_SUBSCRIBE_PRICE_ID",

  "FIREBASE_PROJECT_ID",
  "FIREBASE_CLIENT_EMAIL",
  "FIREBASE_PRIVATE_KEY",

  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "EMAIL_WORKER_URL",
  "EMAIL_WORKER_API_KEY",

  "LIB_SQL_DB_URL",
  "LIB_SQL_AUTH_TOKEN",

  "SENTRY_AUTH_TOKEN",

  "DOMAIN",
  "SUPPORT_EMAIL",
  "EMAIL_WEBHOOK_URL",
] as const
const nonVitalKeys = [
  "FIREBASE_API_KEY",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
  "FIREBASE_MEASUREMENT_ID",
  "FIREBASE_STORAGE_EMULATOR_HOST",

  "VERCEL_ENV",
  "VERCEL_URL",
  "VERCEL_BRANCH_URL",
  "NEXT_PUBLIC_VERCEL_URL",

  "PRODUCTION_URL",

  "TEST_EMAIL",
  "SEND_EMAILS_INTERNAL",

  "NODE_ENV",
] as const
export const config = getConfig({ vitalKeys, nonVitalKeys })
